spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/booklibrary
    username: postgres
    password: 1234
server:
  servlet:
    context-path: '/book-library'
springdoc:
  swagger-ui:
    path: '/'
# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: book-library
    description: The service for tracking borrowed books and book readers
  java:
    version: ${java.version}
logging:
  level:
    org.zalando.logbook: TRACE
