library:
  maxNumberOfBooksToBorrow: ${MAXIMUM_NUMBER_OF_BOOKS_FOR_A_READER_TO_BORROW_SIMULTANEOUSLY}
  minAgeOfReaderForRestricted: ${MIMIMUM_AGE_OF_A_READER_FOR_BORROWING_RESTRICTED_BOOKS}
info:
  app:
    name: book-library
    description: The service for tracking borrowed books and book readers
  java:
    version: ${java.version}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/booklibrary
    username: postgres
    password: 1234
  flyway:
    #creates table flyway_schema_history in DB booklibrary and adds in this table record: version:1;script:<< Flyway Baseline >>
    baseline-on-migrate: true
server:
  servlet:
    context-path: '/book-library'
springdoc:
  swagger-ui:
    path: '/'
# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
logging:
  level:
    org.zalando.logbook: TRACE
javamelody:
  # Initialization parameters for JavaMelody
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests
    log: false

    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)

    # to add basic auth:
    #authorized-users: admin:pwd

    # to change the default storage directory:
    #storage-directory: /tmp/javamelody

    # to change the default "/monitoring" path
    #monitoring-path: /admin/performance
