name: Book Library Java Maven Build & Publish Artifact

on:
  push:
    branches:
      - '*'

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile with Maven
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        run: mvn -B compile

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Maven
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        run: mvn -B test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build fat JAR with Maven
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        run: |
          mvn -B package --file pom.xml -DskipTests=true
          # Check if JAR file was built successfully
          if ! ls target/*.jar &> /dev/null; then
            echo "Error: JAR file was not found."
            exit 1
          fi
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Book-Library-Artifact
          path: target/*.jar

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Book-Library-Artifact
          path: target/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to DockerHub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - name: Build Docker image
        run: docker build -t $DOCKER_USER/$DOCKER_REPOSITORY .
      - name: Push Docker image to DockerHub
        run: docker push $DOCKER_USER/$DOCKER_REPOSITORY
