name: Book Library Java Maven Build & Publish Artifact

on:
  push:
    branches:
      - '*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Compile with Maven
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        run: mvn -B compile

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Maven
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        run: mvn -B test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build fat JAR with Maven
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        run: |
          mvn -B package --file pom.xml -DskipTests=true
          # Store the built JAR as a pipeline artifact
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Book-Library-Artifact
          path: target/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # Fetch the JAR file from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Book-Library-Artifact
          path: target/
      # Proceed with publish steps
      - name: Verify with Maven
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.defaultLogLevel=info"
        run: mvn --batch-mode --update-snapshots verify -DskipTests=true
      - name: Create staging directory and copy artifact
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Book-Library-Artifact
          path: staging
