name: CI Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Compile
      run: |
        # Виконати компіляцію вашого коду тут
        # Наприклад:
        javac -d build src/*.java
        # або
        # mvn compile

    - name: Test
      run: |
        # Запустити всі тести тут
        # Наприклад:
        java -jar test.jar
        # або
        # mvn test

    - name: Build
      run: |
        # Побудувати *.jar артефакт тут
        # Наприклад:
        jar -cvf myapp.jar -C build/ .
        # або
        # mvn package
