name: Book Library Java Maven Build & Publish Artifact

on:
  push:
    branches:
      - '*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile with Maven
      run: mvn -B compile

  test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test with Maven
      run: mvn -B test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build fat JAR with Maven
      run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Verify with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Create staging directory and copy artifact
      run: mkdir staging && cp target/*.jar staging
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Book-Library-Artifact
        path: staging
